#!/usr/bin/env bash
# Generate the canjv formula from the published PyPI wheel's URL and checksum.
# Usage: VERSION=3.0.2 WHEEL_URL=... SHA256=... bash generate_formula.sh
set -euo pipefail

: "${VERSION:?set VERSION}"
: "${WHEEL_URL:?set WHEEL_URL from PyPI release metadata}"
: "${SHA256:?set SHA256 from PyPI release metadata}"

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "Expected a stable release version" >&2; exit 1; }
[[ "$WHEEL_URL" =~ ^https://files\.pythonhosted\.org/[a-zA-Z0-9/_.-]+\.whl$ ]] || { echo "Expected a PyPI wheel URL" >&2; exit 1; }
[[ "$SHA256" =~ ^[a-f0-9]{64}$ ]] || { echo "Expected a SHA256 digest" >&2; exit 1; }

cat <<EOF
# Auto-generated by codeanalyzer-java's release workflow; do not edit by hand.
class CodeanalyzerJava < Formula
  desc "CLDK Java analyzer (canjv), with a bundled JVM"
  homepage "https://github.com/codellm-devkit/codeanalyzer-java"
  url "${WHEEL_URL}", using: :nounzip
  sha256 "${SHA256}"
  version "${VERSION}"
  license "Apache-2.0"

  depends_on "uv"

  # Resolve the wheel and its platform-specific jdk4py runtime on first use,
  # outside Homebrew's build-time network sandbox (same pattern as canpy).
  def install
    (bin/"canjv").write <<~SH
      #!/bin/bash
      exec "#{Formula["uv"].opt_bin}/uvx" --from "codeanalyzer-java==#{version}" canjv "\$@"
    SH
    chmod 0755, bin/"canjv"
  end

  def caveats
    <<~EOS
      The first canjv invocation downloads the pinned PyPI package and its
      bundled JVM through uv. Internet access is required on first use.
    EOS
  end

  test do
    assert_match "codeanalyzer-java==#{version}", File.read(bin/"canjv")
    assert_predicate bin/"canjv", :executable?
  end
end
EOF
